events {
    # 1024 simultaneous connections per worker and sometimes your number of CPU cores determines the number of workers
    worker_connections 1024;
}

http {
   # my_api represents the cluster of the apis.
    upstream my_api {
        server api:3000; 
    }

    # ngnix server
    server {
        listen 80; # Nginix listens on its internal port 80

        
        # When a request hits port 8080 (as per 8080:80 on docker-compose), it gets proxied to port 3000 
        location / {
            proxy_pass http://my_api;
            
            # These headers make sure the API knows the original user's IP, 
            # instead of thinking every request is coming from Nginx.
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}